"""baseline schema

Revision ID: a99b78060eb1
Revises: 
Create Date: 2026-04-28 15:05:28.752419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a99b78060eb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('rules_json', sa.Text(), nullable=False),
    sa.Column('side_bets_json', sa.Text(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('settings_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_template_game_type'), ['game_type'], unique=False)

    op.create_table('game_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('rules_json', sa.Text(), nullable=False),
    sa.Column('side_bets_json', sa.Text(), nullable=False),
    sa.Column('starting_bankroll', sa.Integer(), nullable=False),
    sa.Column('bankroll', sa.Integer(), nullable=False),
    sa.Column('last_results_json', sa.Text(), nullable=False),
    sa.Column('shoe_seed', sa.Integer(), nullable=False),
    sa.Column('cards_dealt', sa.Integer(), nullable=False),
    sa.Column('running_count', sa.Integer(), nullable=False),
    sa.Column('counter_cards_seen', sa.Integer(), nullable=False),
    sa.Column('player_seat', sa.Integer(), nullable=False),
    sa.Column('ai_seats_json', sa.Text(), nullable=False),
    sa.Column('active_round_json', sa.Text(), nullable=True),
    sa.Column('hands_played', sa.Integer(), nullable=False),
    sa.Column('book_profit', sa.Integer(), nullable=False),
    sa.Column('actual_profit', sa.Integer(), nullable=False),
    sa.Column('book_mistakes', sa.Integer(), nullable=False),
    sa.Column('ev_lost_cents', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('pushes', sa.Integer(), nullable=False),
    sa.Column('player_blackjacks', sa.Integer(), nullable=False),
    sa.Column('busts', sa.Integer(), nullable=False),
    sa.Column('surrenders', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['settings_template.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('poker_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('variant_json', sa.Text(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('seats_json', sa.Text(), nullable=False),
    sa.Column('dealer_seat', sa.Integer(), nullable=False),
    sa.Column('active_hand_json', sa.Text(), nullable=True),
    sa.Column('hands_played', sa.Integer(), nullable=False),
    sa.Column('starting_bankroll', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['settings_template.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poker_session')
    op.drop_table('game_session')
    with op.batch_alter_table('settings_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_template_game_type'))

    op.drop_table('settings_template')
    # ### end Alembic commands ###
